### ISSUE TITLE
Delete VIP failed, due to used by load balancer

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#108] opened 2015-08-22 03:02 UTC
If VIP is used by Load Balancer, it can't be deleted so far.

2015-08-22 10:58:58,846 DEBUG [apibinding.api] async call[url: http://10.0.101.20:8080/zstack/api/, request: {"org.zstack.network.service.vip.APIDeleteVipMsg": {"session": {"uuid": "b1cfdddf40ed4d098b57c72d7be10341"}, "uuid": "74ece6e033984d2d8b11d079a87ce3e5", "sessionUuid": "b1cfdddf40ed4d098b57c72d7be10341"}}]
2015-08-22 10:58:59,353 DEBUG [apibinding.api] async call[url: http://10.0.101.20:8080/zstack/api/, response: {"org.zstack.header.message.APIEvent":{"success":false,"error":{"code":"SYS.1006","description":"An operation failed","details":"vip[uuid:74ece6e033984d2d8b11d079a87ce3e5] is still used by the service[LoadBalancer]"}}}]

**Comment by zstackorg** [comment] 2015-08-22 05:38
not a bug, it's design

**Comment by youyk** [comment] 2015-08-22 06:01
This should be aligned with cascade framework. So reopen it.

**Comment by zxwing** [comment] 2015-08-22 06:20
fixed in 72cbfbaf09b692e3830214e5b68e886ba3218015

**Closed by zxwing** 2015-08-22 06:20 UTC
Labels: bug
